#    - name: Persist file
#      uses: actions/upload-artifact@v2
#      with:
#        name: outdir
#        path: out.txt
name: Python application

on:
#  schedule:
#  - cron: "*/5 * * * *"
  
  workflow_dispatch:
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Script
      run: |
        python -m pip install requests
        python test.py > out.txt
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add out.txt
        git commit -m "Job run" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
