name: Repo test

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Script
      run: |
        python -m pip install pyyaml
        python parser.py repositories.yaml out.sh
        chmod +x out.sh
    - name: Clone repos
      run: ./out.sh
    - name: List repos
      run: |
        ls aikaterna-cogs
        ls FlapJack-Cogs
