name: Repo test

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#      with:
#        repository: 'https://gitlab.com/Eragon5779/techcogsv3.git'
#        fetch-depth: 0
    - name: Test
      run: git status
#    - name: Print repo content
#      run: ls techcogsv3
