name: Repo test

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Script
      run: |
        python -m pip install yaml
        python parser.py
    - name: Clone repos
      run: ./cloneme.sh
#    - name: Print repo content
#      run: ls techcogsv3
